name: pharmacy_manager
description: إدارة الصيدلية بنظام إشعارات متقدم وتصميم موحّد
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # لدعم تعريب واجهات Flutter
  flutter_localizations:
    sdk: flutter

  # الواجهات الأساسية للمشروع
  provider: ^6.0.0
  file_picker: ^10.1.9
  permission_handler: ^12.0.0+1
  external_path: ^2.2.0
  share_plus: ^11.0.0
  cross_file: ^0.3.4+2

  # إشعارات محليّة (يتطلّب timezone ^0.10.0 فأعلى)
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1

  # جدولة المهام في الخلفية
  workmanager: ^0.6.0

  # خطوط Google
  google_fonts: ^6.2.1

  # الترجمة والتنسيق
  intl: ^0.20.2

  # الوصول إلى الملفات ونظام الملفات
  path_provider: ^2.0.13

  # رسوم بيانية
  fl_chart: ^1.0.0

  # التصدير إلى CSV
  csv: ^6.0.0

  # إنشاء PDF والطباعة
  pdf: ^3.8.1
  printing: ^5.12.3

  # SharedPreferences (مطلوبة في SettingsStore)
  shared_preferences: ^2.5.3

  # حزم Drift (SQLite)
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # لتوليد كود Drift
  drift_dev: ^2.26.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true


